// DEFINE ANY CONTANTS HERE:
export default {
  NAV_LOGIN: "NAV_LOGIN",
  NAV_HOME: "NAV_HOME",
  NAV_SETTING: "NAV_SETTING",
  NAV_MAIN: "NAV_MAIN",
  NAV_REGISTRATION: "NAV_REGISTRATION",

  LOGIN_ACTION: "LOGIN_ACTION",
  LOGIN_SHOW_LOADING: "LOGIN_SHOW_LOADING",
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  REGISTRATION_SHOW_LOADING: "REGISTRATION_SHOW_LOADING",
  REGISTER_ACTION: "REGISTER_ACTION",
  LOGOUT_ACTION: "LOGOUT_ACTION",
  SET_ALERT_MESSAGE: "SET_ALERT_MESSAGE"
}
